on:
  schedule:
  - cron:  "*/60 * * * *"
  workflow_dispatch:

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
    - name: repo-sync
      uses: wei/git-sync@v2
      with:
        source_repo: "https://repo.or.cz/tinycc.git"
        source_branch: "mob"
        destination_repo: "git@github.com:TinyCC/tinycc.git"
        destination_branch: "mob"
        ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
